### ISSUE TITLE
Attempting to verify a sfv file with a 64 character filename fails due to allocating 16 exabytes of RAM

### ISSUE THREAD

**Issue by zkxs** [althonos/cksfv.rs#111]
I'm running cksfv.rs 0.1.2 on Windows 10, installed via `cargo install cksfv`, and I've noticed that verifying a file with `-f` or `-g` fails if the sfv's filename is at least 64 characters long. 

## Reproduction Steps

```shell
$ echo "hi" > data.txt

$ cksfv data.txt > data.sfv

$ cksfv -f data.sfv
--( Verifying: data.sfv )-------------------------------------------------------
data.txt                                          OK
--------------------------------------------------------------------------------
Everything OK

$ mv data.sfv aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

$ cksfv -f aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
memory allocation of 18446744073709551615 bytes failed
```

And again with 63 characters just to demonstrate that 64 is where this case kicks in:
```shell
$ mv aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

$ cksfv -f aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
--( Verifying: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa )
data.txt                                          OK
--------------------------------------------------------------------------------
Everything OK
```

I have no idea what rust version that was compiled against, so I've recompiled it against rust stable 1.67.1, which still fails but with slightly different output:

```shell
$ cksfv -f aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
thread 'main' panicked at 'capacity overflow', library\alloc\src\raw_vec.rs:518:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Finally, I noticed that there's optional mmap support, and testing after `cargo install --features 'mmap' cksfv` yielded no change from the previous result.

**Comment by stensson** [comment]
I have a patch for this ready. If any admin could make me contributor I could create a pull request.
@zkxs @martinlindhe @althonos

**Comment by zkxs** [comment]
Any reason you can't just create the pull request from your fork? Shouldn't need contributor permissions.

**Comment by stensson** [comment]
of course, sorry I'm damaged from working with github corporate at work. will create fork and pull request. 
is it OK if I include another fix while I'm at it? seems windows line endings in some sfv files also makes the program crash.

**Comment by stensson** [comment]
https://github.com/althonos/cksfv.rs/pull/119 opened

**Comment by althonos** [comment]
Thanks @stensson ! I made a new release with the fix :smile:
